### ISSUE TITLE
hellocv.go failes

### ISSUE THREAD

**Issue by aibrahim** [lazywei/go-opencv#50]
Hi guys i'm trying the sample code of hellocv.go and i got this errors:
panic: LoadImage fail

goroutine 1 [running]:
main.main()
	/home/visof/code/go/image.go:22 +0x1c4

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by lazywei** [comment]
1. what's your OS?
2. what's your OpenCV version, and how did you install it?
3. did you use the latest version of go-opencv on GitHub?
