### ISSUE TITLE
webcam_facedetect.go [signal SIGSEGV: segmentation violation code=0x1 addr=0x1f65730 pc=0x405e72]

### ISSUE THREAD

**Issue by Doaxan** [lazywei/go-opencv#73]
go run webcam_facedetect.go      22:27:49 
Press ESC to quit
unexpected fault address 0x1f65730
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f65730 pc=0x405e72]

goroutine 1 [running]:
runtime.throw(0x4d082e, 0x5)
	/usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc42004dda0 sp=0xc42004dd80
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42004ddf8 sp=0xc42004dda0
main.main()
	/home/doaxan/go/src/github.com/lazywei/go-opencv/samples/webcam_facedetect.go:36 +0x2d2 fp=0xc42004df48 sp=0xc42004ddf8
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc42004dfa0 sp=0xc42004df48
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42004dfa8 sp=0xc42004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1
exit status 2

**Comment by Doaxan** [comment]
System:    Host: pc Kernel: 4.4.19-1-MANJARO x86_64 (64 bit) Desktop: N/A
           Distro: Manjaro Linux
Machine:   System: LENOVO (portable) product: Lenovo IdeaPad Y580 v: Lenovo IdeaPad Y580
           Mobo: LENOVO model: Product Name v: Mainboard version
           UEFI: LENOVO v: 5DCN40WW(V2.07) date: 10/10/2012
Battery    BAT1: charge: 3.6 Wh 59.7% condition: 6.0/6.3 Wh (96%)
CPU:       Quad core Intel Core i7-3610QM (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 3300 MHz 1: 1853 MHz 2: 2311 MHz 3: 1671 MHz
           4: 1743 MHz 5: 1658 MHz 6: 2530 MHz 7: 1618 MHz 8: 3122 MHz
Graphics:  Card-1: Intel 3rd Gen Core processor Graphics Controller
           Card-2: NVIDIA GK107M [GeForce GTX 660M]
           Display Server: X.Org 1.17.4 driver: intel
           Resolution: 1920x1080@59.93hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 12.0.1

**Comment by nilsmagnus** [comment]
Hi, 

I am experiencing the same issue. It seems that the rects returned by the 

`faces := cascade.DetectObjects(img)`

is corrupted with invalid memory references. 

Running ubuntu linux 16.06 on a thinkpad.

**Comment by nilsmagnus** [comment]
The other samples seems to work fine, including the "static" facedetection on Lena, so could it be something with the frame grabbed from the webcam? The other webcam-sample works like a charm.

**Comment by Majonsi** [comment]
I have the same issue, anybody had find a solution?
The code crash when the opencv point is create 
```
						opencv.Point{
							value.X() + (value.Width() / 2),
							value.Y() + (value.Height() / 2),
						},
```

**Comment by alenn-m** [comment]
I have the same problem
